In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json 

portfolio = pd.read_csv('C:/Users/Team_17/Data/portfolio.csv')
profile = pd.read_csv('C:/Users/Team_17/Data/profile.csv')
menu = pd.read_csv('C:/Users/Team_17/Data/starbucks_menu_260112.csv')
transcript = pd.read_csv('C:/Users/Team_17/Data/transcript.csv')


print(f"Portfolio: {portfolio.shape}")
print(f"Profile: {profile.shape}")
print(f"Transcript: {transcript.shape}")
print(f"Menu: {menu.shape}")

Portfolio: (10, 7)
Profile: (17000, 6)
Transcript: (306534, 5)
Menu: (195, 13)

### Portfolio 테이블 : 프로모션 자체의 속성 테이블

In [21]:
portfolio.head(5)

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

In [22]:
portfolio.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   reward      10 non-null     int64
 2   channels    10 non-null     str
 3   difficulty  10 non-null     int64
 4   duration    10 non-null     int64
 5   offer_type  10 non-null     str
 6   id          10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

In [23]:
portfolio["offer_type"].value_counts()

offer_type
bogo             4
discount         4
informational    2
Name: count, dtype: int64

In [24]:
portfolio.isnull().sum()

Unnamed: 0    0
reward        0
channels      0
difficulty    0
duration      0
offer_type    0
id            0
dtype: int64

### profile : 고객 프로필 테이블

In [25]:
profile.head()

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN

In [26]:
profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  str
 2   age               17000 non-null  int64
 3   id                17000 non-null  str
 4   became_member_on  17000 non-null  int64
 5   income            14825 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 797.0 KB

In [27]:
profile.isnull().sum()

Unnamed: 0             0
gender              2175
age                    0
id                     0
became_member_on       0
income              2175
dtype: int64

### Transcript : 고객 행동 로그 테이블

In [28]:
transcript.head()

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [29]:
transcript.info()

<class 'pandas.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  str
 2   event       306534 non-null  str
 3   value       306534 non-null  str
 4   time        306534 non-null  int64
dtypes: int64(2), str(3)
memory usage: 11.7 MB

In [31]:
#offer_id가 있고 amount있음
transcript['value'].value_counts()

value
{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'}    14983
{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}    14924
{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'}    14891
{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'}    14835
{'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}    14374
                                                    ...
{'amount': 290.93}                                      1
{'amount': 43.91}                                       1
{'amount': 685.07}                                      1
{'amount': 405.04}                                      1
{'amount': 476.33}                                      1
Name: count, Length: 5121, dtype: int64

In [32]:
transcript.isnull().sum()

Unnamed: 0    0
person        0
event         0
value         0
time          0
dtype: int64

### Menu : 스타벅스 메뉴 테이블

In [33]:
menu.head(2)

,Unnamed: 0,제품코드,제품명,1회 제공량(kcal),포화지방(g),단백질(g),지방(g),트랜스지방(g),나트륨(mg),당류(g),카페인(mg),콜레스테롤(mg),탄수화물(g)
0,0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0

In [34]:
menu[['제품명','1회 제공량(kcal)']]

                       제품명 1회 제공량(kcal)
0              나이트로 바닐라 크림           80
1               나이트로 콜드 브루            5
2                 돌체 콜드 브루          220
3                 리저브 나이트로            5
4                리저브 콜드 브루            5
..                     ...          ...
190     아이스 더블 에스프레소 크림 라떼          190
191  아이스 프렌즈 얼 그레이 베리 티 라떼          280
192      프렌즈 얼 그레이 베리 티 라떼          280
193            유자 배 캐모마일 티          190
194        아이스 유자 배 캐모마일 티          130

[195 rows x 2 columns]

In [35]:
menu.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    195 non-null    int64
 1   제품코드          195 non-null    int64
 2   제품명           195 non-null    str
 3   1회 제공량(kcal)  195 non-null    str
 4   포화지방(g)       195 non-null    str
 5   단백질(g)        195 non-null    str
 6   지방(g)         195 non-null    str
 7   트랜스지방(g)      195 non-null    str
 8   나트륨(mg)       195 non-null    str
 9   당류(g)         195 non-null    str
 10  카페인(mg)       195 non-null    str
 11  콜레스테롤(mg)     195 non-null    str
 12  탄수화물(g)       195 non-null    str
dtypes: int64(2), str(11)
memory usage: 19.9 KB

In [36]:
menu.isnull().sum()

Unnamed: 0      0
제품코드            0
제품명             0
1회 제공량(kcal)    0
포화지방(g)         0
단백질(g)          0
지방(g)           0
트랜스지방(g)        0
나트륨(mg)         0
당류(g)           0
카페인(mg)         0
콜레스테롤(mg)       0
탄수화물(g)         0
dtype: int64