In [115]:
import pandas as pd

# 데이터 로드
portfolio = pd.read_csv("../../Data/portfolio.csv")
profile = pd.read_csv("../../Data/profile.csv")
starbucks_menu = pd.read_csv("../../Data/starbucks_menu_260112.csv")
transcript = pd.read_csv("../../Data/transcript.csv")

#pip install matplotlib seaborn
import matplotlib, seaborn

# 한글 깨짐 방지
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'AppleGothic' # For MacOS

### ```portfolio```

In [105]:
portfolio.shape

(10, 7)

In [119]:
portfolio.columns

Index(['Unnamed: 0', 'reward', 'channels', 'difficulty', 'duration',
       'offer_type', 'id'],
      dtype='str')

In [60]:
portfolio.head()

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

In [32]:
portfolio.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   reward      10 non-null     int64
 2   channels    10 non-null     str
 3   difficulty  10 non-null     int64
 4   duration    10 non-null     int64
 5   offer_type  10 non-null     str
 6   id          10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

In [39]:
portfolio.describe()

       Unnamed: 0     reward  difficulty   duration
count    10.00000  10.000000   10.000000  10.000000
mean      4.50000   4.200000    7.700000   6.500000
std       3.02765   3.583915    5.831905   2.321398
min       0.00000   0.000000    0.000000   3.000000
25%       2.25000   2.000000    5.000000   5.000000
50%       4.50000   4.000000    8.500000   7.000000
75%       6.75000   5.000000   10.000000   7.000000
max       9.00000  10.000000   20.000000  10.000000

In [162]:
portfolio['reward'].value_counts()

reward
5     3
10    2
0     2
2     2
3     1
Name: count, dtype: int64

### ```profile```

In [ ]:
profile.shape

(17000, 6)

In [118]:
profile.columns

Index(['Unnamed: 0', 'gender', 'age', 'id', 'became_member_on', 'income'], dtype='str')

In [59]:
profile.head()

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN

In [ ]:
profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  str
 2   age               17000 non-null  int64
 3   id                17000 non-null  str
 4   became_member_on  17000 non-null  int64
 5   income            14825 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 797.0 KB

In [55]:
profile.describe()

         Unnamed: 0           age  became_member_on         income
count  17000.000000  17000.000000      1.700000e+04   14825.000000
mean    8499.500000     62.531412      2.016703e+07   65404.991568
std     4907.621624     26.738580      1.167750e+04   21598.299410
min        0.000000     18.000000      2.013073e+07   30000.000000
25%     4249.750000     45.000000      2.016053e+07   49000.000000
50%     8499.500000     58.000000      2.017080e+07   64000.000000
75%    12749.250000     73.000000      2.017123e+07   80000.000000
max    16999.000000    118.000000      2.018073e+07  120000.000000

### ```starbucks_menu```

In [108]:
starbucks_menu.shape

(195, 13)

In [117]:
starbucks_menu.columns

Index(['Unnamed: 0', '제품코드', '제품명', '1회 제공량(kcal)', '포화지방(g)', '단백질(g)',
       '지방(g)', '트랜스지방(g)', '나트륨(mg)', '당류(g)', '카페인(mg)', '콜레스테롤(mg)',
       '탄수화물(g)'],
      dtype='str')

In [61]:
starbucks_menu.head()

,Unnamed: 0,제품코드,제품명,1회 제공량(kcal),포화지방(g),단백질(g),지방(g),트랜스지방(g),나트륨(mg),당류(g),카페인(mg),콜레스테롤(mg),탄수화물(g)
0,0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0

In [ ]:
starbucks_menu.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    195 non-null    int64
 1   제품코드          195 non-null    int64
 2   제품명           195 non-null    str
 3   1회 제공량(kcal)  195 non-null    str
 4   포화지방(g)       195 non-null    str
 5   단백질(g)        195 non-null    str
 6   지방(g)         195 non-null    str
 7   트랜스지방(g)      195 non-null    str
 8   나트륨(mg)       195 non-null    str
 9   당류(g)         195 non-null    str
 10  카페인(mg)       195 non-null    str
 11  콜레스테롤(mg)     195 non-null    str
 12  탄수화물(g)       195 non-null    str
dtypes: int64(2), str(11)
memory usage: 19.9 KB

In [79]:
starbucks_menu.describe()

       Unnamed: 0          제품코드
count  195.000000  1.950000e+02
mean    97.000000  7.061368e+12
std     56.435804  3.764909e+12
min      0.000000  2.000000e+00
25%     48.500000  4.004000e+12
50%     97.000000  9.200000e+12
75%    145.500000  9.200000e+12
max    194.000000  9.900000e+12

### ```transcript```
- ```행동 로그(event log)```(=핵심 테이블)

In [109]:
transcript.shape

(306534, 5)

In [116]:
transcript.columns

Index(['Unnamed: 0', 'person', 'event', 'value', 'time'], dtype='str')

In [62]:
transcript.head()

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [34]:
transcript.info()

<class 'pandas.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  str
 2   event       306534 non-null  str
 3   value       306534 non-null  str
 4   time        306534 non-null  int64
dtypes: int64(2), str(3)
memory usage: 11.7 MB

In [57]:
transcript.describe()

          Unnamed: 0           time
count  306534.000000  306534.000000
mean   153266.500000     366.382940
std     88488.888045     200.326314
min         0.000000       0.000000
25%     76633.250000     186.000000
50%    153266.500000     408.000000
75%    229899.750000     528.000000
max    306533.000000     714.000000

In [100]:
# 결측치
print(f'portfolio 결측치: \n{portfolio.isna().sum()}\n')
print(f'profile 결측치: \n{profile.isna().sum()}\n')
print(f'starbucks_menu 결측치: \n{starbucks_menu.isna().sum()}\n')
print(f'transcript 결측치: \n{transcript.isna().sum()}\n')

portfolio 결측치:
Unnamed: 0    0
reward        0
channels      0
difficulty    0
duration      0
offer_type    0
id            0
dtype: int64

profile 결측치:
Unnamed: 0             0
gender              2175
age                    0
id                     0
became_member_on       0
income              2175
dtype: int64

starbucks_menu 결측치:
Unnamed: 0      0
제품코드            0
제품명             0
1회 제공량(kcal)    0
포화지방(g)         0
단백질(g)          0
지방(g)           0
트랜스지방(g)        0
나트륨(mg)         0
당류(g)           0
카페인(mg)         0
콜레스테롤(mg)       0
탄수화물(g)         0
dtype: int64

transcript 결측치:
Unnamed: 0    0
person        0
event         0
value         0
time          0
dtype: int64

In [146]:
# 중복 행
print(f'portfolio 중복 행: \n{portfolio.duplicated().sum()}\n')
print(f'profile 중복 행: \n{profile.duplicated().sum()}\n')
print(f'starbucks_menu 중복 행: \n{starbucks_menu.duplicated().sum()}\n')
print(f'transcript 중복 행: \n{transcript.duplicated().sum()}\n')

portfolio 중복 행:
0

profile 중복 행:
0

starbucks_menu 중복 행:
0

transcript 중복 행:
0

In [142]:
# 의미없는 컬럼 제거(=단순 인덱스인 것 같음)
portfolio_drop = portfolio.drop(columns=['Unnamed: 0'])
portfolio_drop

,reward,channels,difficulty,duration,offer_type,id
0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
5,3,"['web', 'email', 'mobile', 'social']",7,7,discount,2298d6c36e964ae4a3e7e9706d1fb8c2
6,2,"['web', 'email', 'mobile', 'social']",10,10,discount,fafdcd668e3743c1bb461111dcafc2a4
7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837
8,5,"['web', 'email', 'mobile', 'social']",5,5,bogo,f19421c1d4aa40978ebb69ca19b0e20d
9,2,"['web', 'email', 'mobile']",10,7,discount,2906b810c7d4411798c6938adc9daaa5

In [144]:
profile_drop = profile.drop(columns=['Unnamed: 0'])
profile_drop

,gender,age,id,became_member_on,income
0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN
...,...,...,...,...,...
16995,F,45,6d5f3a774f3d4714ab0c092238f3a1d7,20180604,54000.0
16996,M,61,2cb4f97358b841b9a9773a7aa05a9d77,20180713,72000.0
16997,M,49,01d26f638c274aa0b965d24cefe3183f,20170126,73000.0
16998,F,83,9dc1421481194dcd9400aec7c9ae6366,20160307,50000.0
16999,F,62,e4052622e5ba45a8b96b59aba68cf068,20170722,82000.0

In [148]:
starbucks_menu_drop = starbucks_menu.drop(columns=['Unnamed: 0'])
starbucks_menu_drop

,제품코드,제품명,1회 제공량(kcal),포화지방(g),단백질(g),지방(g),트랜스지방(g),나트륨(mg),당류(g),카페인(mg),콜레스테롤(mg),탄수화물(g)
0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
190,9200000003255,아이스 더블 에스프레소 크림 라떼,190,7,5,9,0,85,20,90,15,21
191,9200000006643,아이스 프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
192,9200000006640,프렌즈 얼 그레이 베리 티 라떼,280,12,4,15,0,60,26,30,15,33
193,9200000006646,유자 배 캐모마일 티,190,0,0,0.2,0,0,33,0,0,52
194,9200000006649,아이스 유자 배 캐모마일 티,130,0,0,0.1,0,0,24,0,0,36

In [150]:
transcript_drop = transcript.drop(columns=['Unnamed: 0'])
transcript_drop

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0
...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.5899999999999999},714
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.5300000000000002},714
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714

In [ ]:
transcript_drop['person'].value_counts()

person
94de646f7b6041228ca7dec82adb97d2    51
8dbfa485249f409aa223a2130f40634a    49
79d9d4f86aca4bed9290350fb43817c2    48
d0a80415b84c4df4908b8403b19765e3    48
5e60c6aa3b834e44b822ea43a3efea26    48
                                    ..
fccc9279ba56411f80ffe8ce7e0935cd     2
22617705eec442e0b7b43e5c5f56fb17     2
912b9f623b9e4b4eb99b6dc919f09a93     2
3045af4e98794a04a5542d3eac939b1f     2
da7a7c0dcfcb41a8acc7864a53cf60fb     1
Name: count, Length: 17000, dtype: int64

In [ ]:
transcript_drop['event'].value_counts()

event
transaction        138953
offer received      76277
offer viewed        57725
offer completed     33579
Name: count, dtype: int64

In [ ]:
# 딕셔너리 형태 -> 변환 필요
transcript_drop['value'].value_counts()

value
{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'}    14983
{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'}    14924
{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'}    14891
{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'}    14835
{'offer id': 'ae264e3637204a6fb9bb56bc8210ddfd'}    14374
                                                    ...
{'amount': 290.93}                                      1
{'amount': 43.91}                                       1
{'amount': 685.07}                                      1
{'amount': 405.04}                                      1
{'amount': 476.33}                                      1
Name: count, Length: 5121, dtype: int64

In [161]:
transcript_drop['time'].value_counts()

time
408    17030
576    17015
504    16822
336    16302
168    16150
       ...
318      940
330      938
156      914
162      910
150      894
Name: count, Length: 120, dtype: int64