In [1]:
import pandas as pd 
df = pd.read_csv('C:/Users/USER/Team_17/Data/portfolio.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,reward,channels,difficulty,duration,offer_type,id
0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   reward      10 non-null     int64
 1   channels    10 non-null     str
 2   difficulty  10 non-null     int64
 3   duration    10 non-null     int64
 4   offer_type  10 non-null     str
 5   id          10 non-null     str
dtypes: int64(3), str(3)
memory usage: 612.0 bytes

In [4]:
df.value_counts()

reward  channels                              difficulty  duration  offer_type     id
10      ['email', 'mobile', 'social']         10          7         bogo           ae264e3637204a6fb9bb56bc8210ddfd    1
        ['web', 'email', 'mobile', 'social']  10          5         bogo           4d5c57ea9a6940dd891ad53e9dbe8da0    1
0       ['web', 'email', 'mobile']            0           4         informational  3f207df678b143eea3cee63160fa8bed    1
5       ['web', 'email', 'mobile']            5           7         bogo           9b98b8c7a33c4b65b9aebfe6a799e6d9    1
        ['web', 'email']                      20          10        discount       0b1e1539f2cc45b7b9fa7c272da2e1d7    1
3       ['web', 'email', 'mobile', 'social']  7           7         discount       2298d6c36e964ae4a3e7e9706d1fb8c2    1
2       ['web', 'email', 'mobile', 'social']  10          10        discount       fafdcd668e3743c1bb461111dcafc2a4    1
0       ['email', 'mobile', 'social']         0           3         informational  5a8bc65990b245e5a138643cd4eb9837    1
5       ['web', 'email', 'mobile', 'social']  5           5         bogo           f19421c1d4aa40978ebb69ca19b0e20d    1
2       ['web', 'email', 'mobile']            10          7         discount       2906b810c7d4411798c6938adc9daaa5    1
Name: count, dtype: int64

In [5]:
df.describe()

          reward  difficulty   duration
count  10.000000   10.000000  10.000000
mean    4.200000    7.700000   6.500000
std     3.583915    5.831905   2.321398
min     0.000000    0.000000   3.000000
25%     2.000000    5.000000   5.000000
50%     4.000000    8.500000   7.000000
75%     5.000000   10.000000   7.000000
max    10.000000   20.000000  10.000000

In [6]:
df.duplicated().sum()

np.int64(0)