In [1]:
import pandas as pd 
df = pd.read_csv('C:/Users/USER/Team_17/Data/profile.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

  gender  age                                id  became_member_on    income
0    NaN  118  68be06ca386d4c31939f3a4f0e3dd783          20170212       NaN
1      F   55  0610b486422d4921ae7d2bf64640c50b          20170715  112000.0
2    NaN  118  38fe809add3b4fcf9315a9694bb96ff5          20180712       NaN
3      F   75  78afa995795e4d85b5d9ceeca43f5fef          20170509  100000.0
4    NaN  118  a03223e636434f42ac4c3df47e8bac43          20170804       NaN

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            14825 non-null  str
 1   age               17000 non-null  int64
 2   id                17000 non-null  str
 3   became_member_on  17000 non-null  int64
 4   income            14825 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 664.2 KB

In [3]:
df.value_counts()

gender  age  id                                became_member_on  income
F       55   0610b486422d4921ae7d2bf64640c50b  20170715          112000.0    1
        75   78afa995795e4d85b5d9ceeca43f5fef  20170509          100000.0    1
M       68   e2127556f4f64592b11af22de27a7932  20180426          70000.0     1
        65   389bc3fa690240e798340f5a15918d5c  20180209          53000.0     1
        58   2eeac8d8feae4a8cad5a6af0499a211d  20171111          51000.0     1
                                                                            ..
F       45   6d5f3a774f3d4714ab0c092238f3a1d7  20180604          54000.0     1
M       61   2cb4f97358b841b9a9773a7aa05a9d77  20180713          72000.0     1
        49   01d26f638c274aa0b965d24cefe3183f  20170126          73000.0     1
F       83   9dc1421481194dcd9400aec7c9ae6366  20160307          50000.0     1
        62   e4052622e5ba45a8b96b59aba68cf068  20170722          82000.0     1
Name: count, Length: 14825, dtype: int64

In [4]:
df.describe()

                age  became_member_on         income
count  17000.000000      1.700000e+04   14825.000000
mean      62.531412      2.016703e+07   65404.991568
std       26.738580      1.167750e+04   21598.299410
min       18.000000      2.013073e+07   30000.000000
25%       45.000000      2.016053e+07   49000.000000
50%       58.000000      2.017080e+07   64000.000000
75%       73.000000      2.017123e+07   80000.000000
max      118.000000      2.018073e+07  120000.000000

In [5]:
df.duplicated().sum()

np.int64(0)