In [1]:
import pandas as pd 
df = pd.read_csv('C:/Users/USER/Team_17/Data/starbucks_menu_260112.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,제품코드,제품명,1회 제공량(kcal),포화지방(g),단백질(g),지방(g),트랜스지방(g),나트륨(mg),당류(g),카페인(mg),콜레스테롤(mg),탄수화물(g)
0,9200000002487,나이트로 바닐라 크림,80,2,1,2.7,0,40,10,232,5,10
1,9200000000479,나이트로 콜드 브루,5,0,0,0,0,5,0,245,0,0
2,9200000002081,돌체 콜드 브루,220,6,6,10,0,80,22,155,20,24
3,9200000002407,리저브 나이트로,5,0,0,0,0,0,0,190,0,0
4,9200000002093,리저브 콜드 브루,5,0,0,0,0,0,0,190,0,0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   제품코드          195 non-null    int64
 1   제품명           195 non-null    str
 2   1회 제공량(kcal)  195 non-null    str
 3   포화지방(g)       195 non-null    str
 4   단백질(g)        195 non-null    str
 5   지방(g)         195 non-null    str
 6   트랜스지방(g)      195 non-null    str
 7   나트륨(mg)       195 non-null    str
 8   당류(g)         195 non-null    str
 9   카페인(mg)       195 non-null    str
 10  콜레스테롤(mg)     195 non-null    str
 11  탄수화물(g)       195 non-null    str
dtypes: int64(1), str(11)
memory usage: 18.4 KB

In [3]:
df.value_counts()

제품코드           제품명                   1회 제공량(kcal)  포화지방(g)  단백질(g)  지방(g)  트랜스지방(g)  나트륨(mg)  당류(g)  카페인(mg)  콜레스테롤(mg)  탄수화물(g)
9200000006619  아이스 프렌즈 시나몬 돌체폼 카푸치노  230           6        6       9      0         95       26     75       20         31         2
9200000006616  프렌즈 시나몬 돌체폼 카푸치노      265           7        8       11     0         120      29     75       25         33         2
9200000003252  더블 에스프레소 크림 라떼        240           8        8       12     0         120      24     90       25         25         2
9200000003255  아이스 더블 에스프레소 크림 라떼    190           7        5       9      0         85       20     90       15         21         2
9200000006646  유자 배 캐모마일 티           190           0        0       0.2    0         0        33     0        0          52         2
                                                                                                                                   ..
5210008072     케일&사과주스 190ML         105           0        0       0      0         25       26     0        0          26         1
5210008055     한라봉주스 190ML           88            0        1       0      0         10       20     0        0          21         1
9300000002565  햇사과 주스 190ML          113           0        0.2     0      0         10       27     0        0          28         1
9300000003775  딸기 가득 요거트 190ML       155           3.2      4       5      0.2       50       21     0        15         23         1
5210008063     블루베리 요거트 190ML        155           3.6      5       6      0.2       70       18     0        20         21         1
Name: count, Length: 187, dtype: int64

In [4]:
df.describe()

               제품코드
count  1.950000e+02
mean   7.061368e+12
std    3.764909e+12
min    2.000000e+00
25%    4.004000e+12
50%    9.200000e+12
75%    9.200000e+12
max    9.900000e+12

In [5]:
df.duplicated().sum()

np.int64(8)