In [1]:
import pandas as pd 
df = pd.read_csv('C:/Users/USER/Team_17/Data/transcript.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df.head()

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   person  306534 non-null  str
 1   event   306534 non-null  str
 2   value   306534 non-null  str
 3   time    306534 non-null  int64
dtypes: int64(1), str(3)
memory usage: 9.4 MB

In [3]:
df.value_counts()

person                            event            value                                                           time
3526938fb466470190a504a751ec07b0  offer completed  {'offer_id': '0b1e1539f2cc45b7b9fa7c272da2e1d7', 'reward': 5}   510     3
3dde94fa581145cb9f206624f1a94d5a  offer completed  {'offer_id': '2906b810c7d4411798c6938adc9daaa5', 'reward': 2}   168     2
e9fb6ed2cecb4980ba98c86abc9c91e3  offer completed  {'offer_id': 'ae264e3637204a6fb9bb56bc8210ddfd', 'reward': 10}  168     2
a7dc060f6fc94ca7bf71fbb188187dca  offer completed  {'offer_id': '9b98b8c7a33c4b65b9aebfe6a799e6d9', 'reward': 5}   168     2
30478a4c1e884a63a822aa87b833ed7a  offer completed  {'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2', 'reward': 3}   168     2
                                                                                                                          ..
b3a1272bc9904337b331bf348c3e8c17  transaction      {'amount': 1.5899999999999999}                                  714     1
68213b08d99a4ae1b0dcb72aebd9aa35  transaction      {'amount': 9.53}                                                714     1
a00058cf10334a308c68e7631c529907  transaction      {'amount': 3.61}                                                714     1
76ddbd6576844afe811f1a3c0fbb5bec  transaction      {'amount': 3.5300000000000002}                                  714     1
c02b10e8752c4d8e9b73f918558531f7  transaction      {'amount': 4.05}                                                714     1
Name: count, Length: 306137, dtype: int64

In [4]:
df.describe()

                time
count  306534.000000
mean      366.382940
std       200.326314
min         0.000000
25%       186.000000
50%       408.000000
75%       528.000000
max       714.000000

In [5]:
df.duplicated().sum()

np.int64(397)